import "./globals.css";

export const metadata = {
  title: "Chat to your Database",
  description: "Generated by Next.js",
  viewport: "width=device-width, initial-scale=1",
  favicon: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen">{children}</body>
    </html>
  );
}
