version: '3'

services:
  nestapp:
    container_name: ctyd-nestapp
    image: ctyd-nestapp
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    networks:
      - ctyd_bridge
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    container_name: ctyd-postgres
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - ctyd_bridge
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ctyd-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - ctyd_bridge
    ports:
      - '5050:80'
    depends_on:
      - postgres

networks:
  ctyd_bridge:
    driver: bridge

volumes:
  pgdata: {}
