version: '3'

services:
  nestapp:
    container_name: ctyd-nestapp
    image: syed007hassan/ctyd-nestapp:latest
    ports:
      - '5000:5000'
    env_file:
      - .env
    networks:
      - ctyd_bridge
    volumes:
      - ${WEBAPP_STORAGE_HOME}/app:/usr/src/app
    depends_on:
      - postgres
      - mongodb

  postgres:
    container_name: ctyd-postgres
    image: syed007hassan/ctyd-postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - ctyd_bridge
    volumes:
      - ${WEBAPP_STORAGE_HOME}/pgdata:/var/lib/postgresql/data
      - ${WEBAPP_STORAGE_HOME}/dbDumpFile:/dbDumpFile

  pgadmin:
    image: syed007hassan/ctyd-pgadmin4:latest
    container_name: ctyd-pgadmin4
    env_file:
      - .env
    networks:
      - ctyd_bridge
    ports:
      - '5050:80'
    depends_on:
      - postgres

  mongodb:
    image: syed007hassan/ctyd-mongo:latest
    container_name: ctyd-mongodb
    env_file:
      - .env
    networks:
      - ctyd_bridge
    ports:
      - '27017:27017'
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ${WEBAPP_STORAGE_HOME}/mongodbdata:/data/db

networks:
  ctyd_bridge:
    driver: bridge

volumes:
  pgdata: {}
  mongodbdata: {}
