version: '3'

services:
  nestapp:
    container_name: ctyd-nestapp
    image: ctyd-nestapp
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    networks:
      - ctyd_bridge
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    container_name: ctyd-postgres
    image: postgres:12
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - ctyd_bridge
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ctyd-pgadmin4
    env_file:
      - .env
    networks:
      - ctyd_bridge
    ports:
      - '5050:80'
    depends_on:
      - postgres

networks:
  ctyd_bridge:
    driver: bridge

volumes:
  pgdata: {}
